{{- if .Values.postgresql.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "glassflow-etl.fullname" . }}-job-reader
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "glassflow-etl.labels" . | nindent 4 }}
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "glassflow-etl.fullname" . }}-job-reader-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "glassflow-etl.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "glassflow-etl.fullname" . }}-job-reader
subjects:
- kind: ServiceAccount
  name: {{ include "glassflow-etl.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
