{{- if and .Values.global.encryption.enabled (not .Values.global.encryption.existingSecret.name) .Values.global.encryption.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.encryption.secretName | default (printf "%s-encryption-key" .Release.Name) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "glassflow-etl.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
type: Opaque
stringData:
  encryption-key: {{ randAlphaNum 32 | quote }}
{{- end }}
