{{- if or .Values.global.observability.metrics.enabled .Values.global.observability.logs.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-otel-collector-config
  namespace: {{ .Release.Namespace }}
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
{{- if and .Values.nats.enabled .Values.global.observability.metrics.enabled }}
      prometheus:
        config:
          scrape_configs:
            - job_name: 'nats-exporter'
              static_configs:
                - targets: ['{{ .Release.Name }}-prometheus-nats-exporter.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.natsPrometheusExporter.service.port }}']
              scrape_interval: 15s
              metrics_path: /metrics
{{- end }}

    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024
      resource:
        attributes:
          - key: service.name
            from_attribute: service.name
            action: insert
          - key: service.version
            from_attribute: service.version
            action: insert
          - key: service.namespace
            from_attribute: service.namespace
            action: insert

    exporters:
{{- if .Values.global.observability.logs.enabled }}
      otlp: {{ toYaml .Values.global.observability.logs.exporter.otlp | nindent 8 }}
{{- end }}
{{- if .Values.global.observability.metrics.enabled }}
      prometheus:
          endpoint: "0.0.0.0:9090"
          namespace: {{ .Release.Namespace }}
          send_timestamps: true
          enable_open_metrics: true
{{- end }}
        
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133

    service:
      extensions: [health_check]
      pipelines:
{{- if .Values.global.observability.logs.enabled }}
        logs:
          receivers: [otlp]
          processors: [batch, resource]
          exporters: [otlp]
{{- end }}
{{- if .Values.global.observability.metrics.enabled }}
        metrics:
          receivers: [otlp{{- if .Values.nats.enabled }}, prometheus{{- end }}]
          processors: [batch, resource]
          exporters: [prometheus]
{{- end }}
{{- end }}
