{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "glassflow-etl.serviceAccountName" . }}
  labels:
    {{- include "glassflow-etl.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.global.usageStats.enabled }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
{{- /* 
     Note: When tracking is enabled, the ServiceAccount is created as a hook to ensure
     it exists before the pre-install tracking hook runs. During uninstall, it will
     still exist as a regular resource until Helm deletes it, allowing pre-delete
     hooks to use it.
*/}}