{{- if false }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tracking-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "glassflow-etl.labels" . | nindent 4 }}
type: Opaque
data:
  tracking_endpoint: {{ .Values.global.usageStats.endpoint | b64enc }}
  tracking_username: {{ .Values.global.usageStats.username | b64enc }}
  tracking_password: {{ .Values.global.usageStats.password | b64enc }}
{{- end }}

