{{- if .Values.global.tracking.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tracking-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "glassflow-etl.labels" . | nindent 4 }}
type: Opaque
data:
  installation_id: ""
  tracking_endpoint: {{ .Values.global.tracking.endpoint | b64enc }}
  tracking_username: {{ .Values.global.tracking.username | b64enc }}
  tracking_password: {{ .Values.global.tracking.password | b64enc }}
{{- end }}

