{{- if false }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-usage-stats-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "glassflow-etl.labels" . | nindent 4 }}
type: Opaque
data:
  usage_stats_endpoint: {{ .Values.global.usageStats.endpoint | b64enc }}
  usage_stats_username: {{ .Values.global.usageStats.username | b64enc }}
  usage_stats_password: {{ .Values.global.usageStats.password | b64enc }}
{{- end }}

