{{- if false }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-usage-stats-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "glassflow-etl.labels" . | nindent 4 }}
type: Opaque
data:
  usage_stats_endpoint: {{ "https://tracking.glassflow.dev/api/v1" | b64enc }}
  usage_stats_username: {{ "5PR3vzYGGlYttkBXRTYuzw==" | b64enc }}
  usage_stats_password: {{ "5tJcYQNR85KKyOwpeIFVdGqGIOgFwxmWEHu0t7WxBbo=" | b64enc }}
{{- end }}

